mod author;
mod commit;
use std::path::PathBuf;

pub use author::*;
pub use commit::*;

mod providers;
pub use providers::*;
use serde::{Deserialize, Serialize};

/// Source metadata and file list for rendering a codebase as a book.
///
/// Created by the config wizard or loaded from `src-book.toml`. The `source_files` list
/// is pre-sorted based on the optional `entrypoint` to ensure logical reading order.
#[derive(Default, Debug, Serialize, Deserialize)]
pub struct Source {
    /// Book title displayed on the title page
    pub title: Option<String>,

    /// Path to the git repository root
    pub repository: PathBuf,

    /// SPDX license identifiers (e.g., "MIT", "Apache-2.0"). Not validated by default.
    pub licenses: Vec<String>,

    /// Optional entrypoint file (e.g., `src/main.rs`) that controls file ordering.
    /// When set, the entrypoint appears first, followed by sibling files in its directory,
    /// then subdirectories, then everything else. Helps readers start at the logical entry
    /// point and follow imports naturally.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entrypoint: Option<PathBuf>,

    /// Source files to include in the book, in display order.
    /// Generated by walking the repository (respecting .gitignore) and sorted by the
    /// entrypoint-aware algorithm if an entrypoint is specified.
    pub source_files: Vec<PathBuf>,

    /// Repository authors extracted from git commit history.
    /// Sorted by prominence (commit count) at render time.
    pub authors: Vec<Author>,
}
